sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: regions
      - name: nations
      - name: nation_info
      - name: orders
        config:
          freshness: # make this a little more strict
            warn_after: {count: 1, period: hour}
            error_after: {count: 1, period: hour}
          loaded_at_field: o_orderdate::timestamp_ntz
      - name: lineitems
      - name: parts
      - name: suppliers
      - name: partsupps

  - name: mkmotors_src
    database: MKMOTORS_DEV
    schema: STAGING
    tables:
      - name: stg_employees

